version: '3.8'

services:
  # ----------------------------------
  # 1) PHP-FPM 컨테이너
  # ----------------------------------
  php:
    build: ./php
    container_name: php_app
    # 컨테이너 내부 /var/www/html 경로에 로컬 app 디렉토리를 마운트
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    networks:
      - mynet
    depends_on:
      - db

  # ----------------------------------
  # 2) Nginx 컨테이너
  # ----------------------------------
  nginx:
    image: nginx:alpine
    container_name: nginx_app
    # Nginx 설정파일과 app 소스코드를 마운트
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - "8080:80"  # 호스트 8080 -> 컨테이너 80
    networks:
      - mynet

  # ----------------------------------
  # 3) MySQL(DB) 컨테이너
  # ----------------------------------
  db:
    image: mysql:8.0
    container_name: db_app
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sports_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mynet

# 네트워크 정의
networks:
  mynet:

# 볼륨 정의 (MySQL 데이터)
volumes:
  db_data:
