version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html    # 프로젝트 루트를 컨테이너 /var/www/html에 마운트
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: mysql:8.0
    container_name: db_app
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sports_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/initdb
    command: --init-file /initdb/init.sql
    ports:
      - "3306:3306"
    networks:
      - mynet

networks:
  mynet:

volumes:
  db_data:
