version: '3.8'

services:
  # ----------------------------------
  # 1) PHP-FPM 컨테이너
  # ----------------------------------
  php:
    build: ./php
    container_name: php_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - mynet

  # ----------------------------------
  # 2) Nginx 컨테이너
  # ----------------------------------
  nginx:
    image: nginx:alpine
    container_name: nginx_app
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - mynet

  # ----------------------------------
  # 3) MySQL(DB) 컨테이너
  # ----------------------------------
  db:
    image: mysql:8.0
    container_name: db_app

    # MySQL root 사용자 비밀번호
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: sports_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass

    # 데이터 영구 보존
    volumes:
      - db_data:/var/lib/mysql
      # init.sql을 /initdb 디렉토리에 마운트
      - ./initdb:/initdb

    # 컨테이너가 켜질 때마다 init.sql 실행 (IF NOT EXISTS로 안전)
    command: --init-file /initdb/init.sql

    ports:
      - "3306:3306"
    networks:
      - mynet

# 네트워크 정의
networks:
  mynet:

# MySQL 데이터 저장용 볼륨
volumes:
  db_data:
